-- DESC books;
-- SELECT CONCAT('h', 'e', 'l', 'l', 'o');
-- SELECT CONCAT(author_fname, author_lname) FROM books;
-- SELECT CONCAT(author_fname, ' ', author_lname) FROM books;
-- SELECT CONCAT(author_fname, ' ', author_lname) AS author_name FROM books;
-- SELECT CONCAT_WS('-', title, author_fname, author_lname) FROM books;